/*
File: ms-iiss.idl
Protocol: [MS-IISS]: Internet Information Services (IIS) ServiceControl Protocol
Source: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-iiss/2a86f63c-569c-4055-aeb0-471e50e090a3
Retrieval Date: Wed Aug 11 14:20:33 2021
*/

 import "ms-dtyp.idl"; 
 import "ms-oaut.idl";
  
  [
   object,
   uuid(E8FB8620-588F-11D2-9D61-00C04F79C5FE),
   dual,
   pointer_default(unique)
  ]
  interface IIisServiceControl : IDispatch
  {
    HRESULT Stop(
           DWORD dwTimeoutMsecs, 
           DWORD dwForce
           );
    HRESULT Start(
           DWORD dwTimeoutMsecs
           );
    HRESULT Reboot( 
           DWORD dwTimeouMsecs, 
           DWORD dwForceAppsClosed 
           );
    HRESULT Status(
           [in] DWORD dwBufferSize, 
           [out, size_is(dwBufferSize)] unsigned char *pbBuffer, 
           [out] DWORD *pdwMDRequiredBufferSize, 
           [out] DWORD *pdwNumServices
           );
    HRESULT Kill();
 };
  
  
  
  
