/*
File: ms-wdsc.idl
Protocol: [MS-WDSC]: Windows Deployment Services Control Protocol
Source: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wdsc/d2d48508-bda0-4dce-b6b2-1c314566a9c5
Retrieval Date: Wed Aug 11 14:27:48 2021
*/

 import "ms-dtyp.idl";
  
 [
     uuid(1A927394-352E-4553-AE3F-7CF4AAFCA620),
     version(1.0)
 ]
 interface WdsRpcInterface
 {
     unsigned long
     WdsRpcMessage(          
       handle_t hBinding,
       [in] unsigned long uRequestPacketSize,
       [in, size_is(uRequestPacketSize)] byte bRequestPacket[],
       [out] unsigned long* puReplyPacketSize,
       [out, size_is(, *puReplyPacketSize)] byte** pbReplyPacket
  
     );
 }
  
