from fuzzer.midl import *
from fuzzer.core import *

interface_0 = Interface(
    "0EAC4842-8763-11cf-A743-00AA00A3F00D",
    "1.0",
    [
        Method(
            "Query",
            In(BSTR),
            In(BSTR),
            In(LONG),
            Out(PPIDISPATCH),
        ),
        Method(
            "SubmitChanges",
            In(BSTR),
            In(PIDISPATCH),
        ),
        Method(
            "ConvertToString",
            In(PIUNKNOWN),
            Out(PBSTR),
        ),
        Method(
            "CreateRecordSet",
            In(VARIANT),
            Out(PPIDISPATCH),
        ),
    ],
)
interface_1 = Interface(
    "070669EB-B52F-11d1-9270-00C04FBBBFB3",
    "1.0",
    [
        Method(
            "Execute21",
            In(BSTR),
            In(BSTR),
            In(BSTR),
            In(LONG),
            In(VARIANT),
            In(VARIANT),
            In(LONG),
            InOut(PVARIANT),
            Out(PPIDISPATCH),
        ),
        Method(
            "Synchronize21",
            In(BSTR),
            In(BSTR),
            In(LONG),
            InOut(PPIDISPATCH),
            InOut(PVARIANT),
            Out(PVARIANT),
        ),
    ],
)
interface_2 = Interface(
    "4639DB2A-BFC5-11d2-9318-00C04FBBBFB3",
    "1.0",
    [
        Method(
            "Execute",
            In(BSTR),
            In(BSTR),
            In(BSTR),
            In(LONG),
            In(VARIANT),
            In(VARIANT),
            In(LONG),
            InOut(PVARIANT),
            In(LONG),
            InOut(PVARIANT),
            Out(PPIDISPATCH),
        ),
        Method(
            "Synchronize",
            In(BSTR),
            In(BSTR),
            In(LONG),
            InOut(PPIDISPATCH),
            InOut(PVARIANT),
            In(LONG),
            InOut(PVARIANT),
            Out(PVARIANT),
        ),
    ],
)
