
from fuzzer.midl import *
from fuzzer.core import *
ULONGLONG = NdrHyper
BYTE = NdrByte
USHORT = NdrShort
SHORT = NdrShort
UCHAR = NdrByte
PCHAR = NdrByte
PUCHAR = NdrByte
PLONG64 = NdrHyper
ULONG = NdrLong
ULONG64 = NdrHyper
DWORD64 = NdrHyper
PDWORD64 = NdrHyper
DWORD = NdrLong
UINT64 = NdrHyper
WORD = NdrByte
PWCHAR_T = NdrByte
BOOLEAN = NdrBoolean
__INT64 = NdrHyper
UNSIGNED_SHORT = NdrShort
UNSIGNED_CHAR = NdrByte
UNSIGNED_LONG = NdrLong
UNSIGNEDLONG = NdrLong
PUNSIGNED_LONG = NdrLong
PUNSIGNED_CHAR = NdrByte
UNSIGNED_INT = NdrLong
UNSIGNED___INT64 = NdrHyper
SIGNED___INT64 = NdrHyper
SIGNED_INT = NdrShort
SIGNED_LONG = NdrLong
SIGNED_CHAR = NdrByte
SIGNED_SHORT = NdrShort
WCHAR_T = NdrWString
CHAR = NdrByte
PWCHAR = NdrCString
INT = NdrLong
PVOID = NdrContextHandle
VOID = NdrContextHandle
CONTEXT_HANDLE = NdrContextHandle
PPCONTEXT_HANDLE = NdrContextHandle
LONG = NdrLong
__INT3264 = NdrHyper
UNSIGNED___INT3264 = NdrHyper
UNSIGNED_HYPER = NdrHyper
HYPER = NdrHyper
DWORDLONG = NdrHyper
LONG_PTR = NdrHyper
ULONG_PTR = NdrHyper
LARGE_INTEGER = NdrHyper
LPSTR = NdrCString
LPWSTR = NdrWString
LPCSTR = NdrCString
LPCWSTR = NdrWString
LMSTR = NdrWString
PWSTR = NdrWString
WCHAR = NdrWString
PBYTE = NdrByte
DOUBLE = NdrDouble
FLOAT = NdrFloat

class FILETIME(NdrStructure):
    MEMBERS = [(DWORD,'dwLowDateTime'),(LONG,'dwHighDateTime')]

class LUID(NdrStructure):
    MEMBERS = [(DWORD,'LowPart'),(LONG,'HighPart')]

class SYSTEMTIME(NdrStructure):
    MEMBERS = [(WORD,'wYear'),(WORD,'wMonth'),(WORD,'wDayOfWeek'),(WORD,'wDay'),(WORD,'wHour'),(WORD,'wMinute'),(WORD,'wSecond'),(WORD,'wMilliseconds'),]
WCHAR_T = UNSIGNED_SHORT
ADCONNECTION_HANDLE = VOID
BOOL = INT
PPBOOL = INT
PLPBOOL = INT
BYTE = UNSIGNED_CHAR
PPBYTE = UNSIGNED_CHAR
PLPBYTE = UNSIGNED_CHAR
BOOLEAN = BYTE
PPBOOLEAN = BYTE
WCHAR = WCHAR_T
PPWCHAR = WCHAR_T
BSTR = WCHAR
CHAR = CHAR
PPCHAR = CHAR
DOUBLE = DOUBLE
DWORD = UNSIGNED_LONG
PPDWORD = UNSIGNED_LONG
PLPDWORD = UNSIGNED_LONG
DWORD32 = UNSIGNED_INT
DWORD64 = UNSIGNED___INT64
PPDWORD64 = UNSIGNED___INT64
ULONGLONG = UNSIGNED___INT64
DWORDLONG = ULONGLONG
PPDWORDLONG = ULONGLONG
ERROR_STATUS_T = UNSIGNED_LONG
FLOAT = FLOAT
UCHAR = UNSIGNED_CHAR
PPUCHAR = UNSIGNED_CHAR
SHORT = SHORT
HANDLE = VOID
HCALL = DWORD
INT = INT
PLPINT = INT
INT8 = SIGNED_CHAR
INT16 = SIGNED_SHORT
INT32 = SIGNED_INT
INT64 = SIGNED___INT64
LDAP_UDP_HANDLE = VOID
LMCSTR = WCHAR_T
LMSTR = WCHAR
LONG = LONG
PPLONG = LONG
PLPLONG = LONG
LONGLONG = SIGNED___INT64
HRESULT = LONG
LONG_PTR = __INT3264
ULONG_PTR = UNSIGNED___INT3264
LONG32 = SIGNED_INT
LONG64 = SIGNED___INT64
PPLONG64 = SIGNED___INT64
LPCSTR = CHAR
LPCVOID = VOID
LPCWSTR = WCHAR_T
PSTR = CHAR
PLPSTR = CHAR
LPWSTR = WCHAR_T
PPWSTR = WCHAR_T
NET_API_STATUS = DWORD
NTSTATUS = LONG
PCONTEXT_HANDLE = VOID
PPCONTEXT_HANDLE = PCONTEXT_HANDLE
QWORD = UNSIGNED___INT64
RPC_BINDING_HANDLE = VOID
STRING = UCHAR
UINT = UNSIGNED_INT
UINT8 = UNSIGNED_CHAR
UINT16 = UNSIGNED_SHORT
UINT32 = UNSIGNED_INT
UINT64 = UNSIGNED___INT64
ULONG = UNSIGNED_LONG
PPULONG = UNSIGNED_LONG
DWORD_PTR = ULONG_PTR
SIZE_T = ULONG_PTR
ULONG32 = UNSIGNED_INT
ULONG64 = UNSIGNED___INT64
UNICODE = WCHAR_T
USHORT = UNSIGNED_SHORT
VOID = VOID
PPVOID = VOID
PLPVOID = VOID
WORD = UNSIGNED_SHORT
PPWORD = UNSIGNED_SHORT
PLPWORD = UNSIGNED_SHORT

class FILETIME(NdrStructure):
    MEMBERS = [(DWORD, "dwLowDateTime"),(DWORD, "dwHighDateTime"),]

    
PFILETIME = FILETIME
LPFILETIME = FILETIME

class GUID(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Data1"),(UNSIGNED_SHORT, "Data2"),(UNSIGNED_SHORT, "Data3"),(BYTE, "Data4"),]

    
UUID = GUID
PGUID = GUID

class LARGE_INTEGER(NdrStructure):
    MEMBERS = [(SIGNED___INT64, "QuadPart"),]

    
PLARGE_INTEGER = LARGE_INTEGER

class EVENT_DESCRIPTOR(NdrStructure):
    MEMBERS = [(USHORT, "Id"),(UCHAR, "Version"),(UCHAR, "Channel"),(UCHAR, "Level"),(UCHAR, "Opcode"),(USHORT, "Task"),(ULONGLONG, "Keyword"),]

    
PEVENT_DESCRIPTOR = EVENT_DESCRIPTOR
PCEVENT_DESCRIPTOR = EVENT_DESCRIPTOR

class S0(NdrStructure):
    MEMBERS = [(ULONG, "KernelTime"),(ULONG, "UserTime"),]

    

class U0(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (S0, "s0"),2 : (ULONG64, "ProcessorTime"),}

    

class EVENT_HEADER(NdrStructure):
    MEMBERS = [(USHORT, "Size"),(USHORT, "HeaderType"),(USHORT, "Flags"),(USHORT, "EventProperty"),(ULONG, "ThreadId"),(ULONG, "ProcessId"),(LARGE_INTEGER, "TimeStamp"),(GUID, "ProviderId"),(EVENT_DESCRIPTOR, "EventDescriptor"),(U0, "u0"),(GUID, "ActivityId"),]

    
PEVENT_HEADER = EVENT_HEADER
LCID = DWORD

class LUID(NdrStructure):
    MEMBERS = [(DWORD, "LowPart"),(LONG, "HighPart"),]

    
PLUID = LUID

class MULTI_SZ(NdrStructure):
    MEMBERS = [(PWCHAR_T, "Value"),(DWORD, "nChar"),]

    

class RPC_UNICODE_STRING(NdrStructure):
    MEMBERS = [(UNSIGNED_SHORT, "Length"),(UNSIGNED_SHORT, "MaximumLength"),(PWCHAR, "Buffer"),]

    
PRPC_UNICODE_STRING = RPC_UNICODE_STRING

class SERVER_INFO_100(NdrStructure):
    MEMBERS = [(DWORD, "sv100_platform_id"),(PWCHAR_T, "sv100_name"),]

    
PSERVER_INFO_100 = SERVER_INFO_100
LPSERVER_INFO_100 = SERVER_INFO_100

class SERVER_INFO_101(NdrStructure):
    MEMBERS = [(DWORD, "sv101_platform_id"),(PWCHAR_T, "sv101_name"),(DWORD, "sv101_version_major"),(DWORD, "sv101_version_minor"),(DWORD, "sv101_version_type"),(PWCHAR_T, "sv101_comment"),]

    
PSERVER_INFO_101 = SERVER_INFO_101
LPSERVER_INFO_101 = SERVER_INFO_101

class SYSTEMTIME(NdrStructure):
    MEMBERS = [(WORD, "wYear"),(WORD, "wMonth"),(WORD, "wDayOfWeek"),(WORD, "wDay"),(WORD, "wHour"),(WORD, "wMinute"),(WORD, "wSecond"),(WORD, "wMilliseconds"),]

    
PSYSTEMTIME = SYSTEMTIME

class UINT128(NdrStructure):
    MEMBERS = [(UINT64, "lower"),(UINT64, "upper"),]

    
PUINT128 = UINT128

class ULARGE_INTEGER(NdrStructure):
    MEMBERS = [(UNSIGNED___INT64, "QuadPart"),]

    
PULARGE_INTEGER = ULARGE_INTEGER

class RPC_SID_IDENTIFIER_AUTHORITY(NdrStructure):
    MEMBERS = [(BYTE, "Value"),]

    
ACCESS_MASK = DWORD
PACCESS_MASK = ACCESS_MASK

class OBJECT_TYPE_LIST(NdrStructure):
    MEMBERS = [(WORD, "Level"),(ACCESS_MASK, "Remaining"),(PGUID, "ObjectType"),]

    
POBJECT_TYPE_LIST = OBJECT_TYPE_LIST

class ACE_HEADER(NdrStructure):
    MEMBERS = [(UCHAR, "AceType"),(UCHAR, "AceFlags"),(USHORT, "AceSize"),]

    
PACE_HEADER = ACE_HEADER

class SYSTEM_MANDATORY_LABEL_ACE(NdrStructure):
    MEMBERS = [(ACE_HEADER, "Header"),(ACCESS_MASK, "Mask"),(DWORD, "SidStart"),]

    
PSYSTEM_MANDATORY_LABEL_ACE = SYSTEM_MANDATORY_LABEL_ACE

class TOKEN_MANDATORY_POLICY(NdrStructure):
    MEMBERS = [(DWORD, "Policy"),]

    
PTOKEN_MANDATORY_POLICY = TOKEN_MANDATORY_POLICY

class MANDATORY_INFORMATION(NdrStructure):
    MEMBERS = [(ACCESS_MASK, "AllowedAccess"),(BOOLEAN, "WriteAllowed"),(BOOLEAN, "ReadAllowed"),(BOOLEAN, "ExecuteAllowed"),(TOKEN_MANDATORY_POLICY, "MandatoryPolicy"),]

    
PMANDATORY_INFORMATION = MANDATORY_INFORMATION

class CLAIM_SECURITY_ATTRIBUTE_OCTET_STRING_RELATIVE(NdrStructure):
    MEMBERS = [(DWORD, "Length"),(BYTE, "OctetString"),]

    
PCLAIM_SECURITY_ATTRIBUTE_OCTET_STRING_RELATIVE = CLAIM_SECURITY_ATTRIBUTE_OCTET_STRING_RELATIVE

class VALUES(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (PLONG64, "pInt64"),2 : (PDWORD64, "pUint64"),3 : (PWSTR, "ppString"),4 : (PCLAIM_SECURITY_ATTRIBUTE_OCTET_STRING_RELATIVE, "pOctetString"),}

    

class CLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1(NdrStructure):
    MEMBERS = [(DWORD, "Name"),(WORD, "ValueType"),(WORD, "Reserved"),(DWORD, "Flags"),(DWORD, "ValueCount"),(VALUES, "Values"),]

    
PCLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1 = CLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1
SECURITY_INFORMATION = DWORD
PPSECURITY_INFORMATION = DWORD

class RPC_SID(NdrStructure):
    MEMBERS = [(UNSIGNED_CHAR, "Revision"),(UNSIGNED_CHAR, "SubAuthorityCount"),(RPC_SID_IDENTIFIER_AUTHORITY, "IdentifierAuthority"),(UNSIGNED_LONG, "SubAuthority"),]

    
PRPC_SID = RPC_SID
PSID = RPC_SID

class ACL(NdrStructure):
    MEMBERS = [(UNSIGNED_CHAR, "AclRevision"),(UNSIGNED_CHAR, "Sbz1"),(UNSIGNED_SHORT, "AclSize"),(UNSIGNED_SHORT, "AceCount"),(UNSIGNED_SHORT, "Sbz2"),]

    
PACL = ACL

class SECURITY_DESCRIPTOR(NdrStructure):
    MEMBERS = [(UCHAR, "Revision"),(UCHAR, "Sbz1"),(USHORT, "Control"),(PSID, "Owner"),(PSID, "Group"),(PACL, "Sacl"),(PACL, "Dacl"),]

    
PSECURITY_DESCRIPTOR = SECURITY_DESCRIPTOR

class RPC_STRING(NdrStructure):
    MEMBERS = [(UNSIGNED_SHORT, "Length"),(UNSIGNED_SHORT, "MaximumLength"),(PCHAR, "Buffer"),]

    
PRPC_STRING = RPC_STRING

class OLD_LARGE_INTEGER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "LowPart"),(LONG, "HighPart"),]

    
POLD_LARGE_INTEGER = OLD_LARGE_INTEGER
PSAMPR_SERVER_NAME = WCHAR_T
SAMPR_HANDLE = VOID

class ENCRYPTED_LM_OWF_PASSWORD(NdrStructure):
    MEMBERS = [(CHAR, "data"),]

    
PENCRYPTED_LM_OWF_PASSWORD = ENCRYPTED_LM_OWF_PASSWORD
ENCRYPTED_NT_OWF_PASSWORD = ENCRYPTED_LM_OWF_PASSWORD
PENCRYPTED_NT_OWF_PASSWORD = ENCRYPTED_LM_OWF_PASSWORD

class SAMPR_ULONG_ARRAY(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Count"),(PUNSIGNED_LONG, "Element"),]

    
PSAMPR_ULONG_ARRAY = SAMPR_ULONG_ARRAY

class SAMPR_SID_INFORMATION(NdrStructure):
    MEMBERS = [(PRPC_SID, "SidPointer"),]

    
PSAMPR_SID_INFORMATION = SAMPR_SID_INFORMATION

class SAMPR_PSID_ARRAY(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Count"),(PSAMPR_SID_INFORMATION, "Sids"),]

    
PSAMPR_PSID_ARRAY = SAMPR_PSID_ARRAY

class SAMPR_PSID_ARRAY_OUT(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Count"),(PSAMPR_SID_INFORMATION, "Sids"),]

    
PSAMPR_PSID_ARRAY_OUT = SAMPR_PSID_ARRAY_OUT

class SAMPR_RETURNED_USTRING_ARRAY(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Count"),(PRPC_UNICODE_STRING, "Element"),]

    
PSAMPR_RETURNED_USTRING_ARRAY = SAMPR_RETURNED_USTRING_ARRAY

class SID_NAME_USE(NdrEnum):
    MAP = ((1 , 'SidTypeUser'),(2 , 'SidTypeGroup'),(3 , 'SidTypeDomain'),(4 , 'SidTypeAlias'),(5 , 'SidTypeWellKnownGroup'),(6 , 'SidTypeDeletedAccount'),(7 , 'SidTypeInvalid'),(8 , 'SidTypeUnknown'),(9 , 'SidTypeComputer'),(10 , 'SidTypeLabel'),)        

class RPC_SHORT_BLOB(NdrStructure):
    MEMBERS = [(UNSIGNED_SHORT, "Length"),(UNSIGNED_SHORT, "MaximumLength"),(PUNSIGNED_SHORT, "Buffer"),]

    
PRPC_SHORT_BLOB = RPC_SHORT_BLOB

class SAMPR_RID_ENUMERATION(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "RelativeId"),(RPC_UNICODE_STRING, "Name"),]

    
PSAMPR_RID_ENUMERATION = SAMPR_RID_ENUMERATION

class SAMPR_ENUMERATION_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "EntriesRead"),(PSAMPR_RID_ENUMERATION, "Buffer"),]

    
PSAMPR_ENUMERATION_BUFFER = SAMPR_ENUMERATION_BUFFER

class SAMPR_SR_SECURITY_DESCRIPTOR(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Length"),(PUNSIGNED_CHAR, "SecurityDescriptor"),]

    
PSAMPR_SR_SECURITY_DESCRIPTOR = SAMPR_SR_SECURITY_DESCRIPTOR

class GROUP_MEMBERSHIP(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "RelativeId"),(UNSIGNED_LONG, "Attributes"),]

    
PGROUP_MEMBERSHIP = GROUP_MEMBERSHIP

class SAMPR_GET_GROUPS_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "MembershipCount"),(PGROUP_MEMBERSHIP, "Groups"),]

    
PSAMPR_GET_GROUPS_BUFFER = SAMPR_GET_GROUPS_BUFFER

class SAMPR_GET_MEMBERS_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "MemberCount"),(PUNSIGNED_LONG, "Members"),(PUNSIGNED_LONG, "Attributes"),]

    
PSAMPR_GET_MEMBERS_BUFFER = SAMPR_GET_MEMBERS_BUFFER

class SAMPR_REVISION_INFO_V1(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Revision"),(UNSIGNED_LONG, "SupportedFeatures"),]

    
PSAMPR_REVISION_INFO_V1 = SAMPR_REVISION_INFO_V1

class SAMPR_REVISION_INFO(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (SAMPR_REVISION_INFO_V1, "V1"),}

    
PSAMPR_REVISION_INFO = SAMPR_REVISION_INFO

class USER_DOMAIN_PASSWORD_INFORMATION(NdrStructure):
    MEMBERS = [(UNSIGNED_SHORT, "MinPasswordLength"),(UNSIGNED_LONG, "PasswordProperties"),]

    
PUSER_DOMAIN_PASSWORD_INFORMATION = USER_DOMAIN_PASSWORD_INFORMATION

class DOMAIN_SERVER_ENABLE_STATE(NdrEnum):
    MAP = ((1 , 'DomainServerEnabled'),(2 , 'DomainServerDisabled'),)        

class DOMAIN_STATE_INFORMATION(NdrStructure):
    MEMBERS = [(DOMAIN_SERVER_ENABLE_STATE, "DomainServerState"),]

    
PDOMAIN_STATE_INFORMATION = DOMAIN_STATE_INFORMATION

class DOMAIN_SERVER_ROLE(NdrEnum):
    MAP = ((2 , 'DomainServerRoleBackup'),(3 , 'DomainServerRolePrimary'),)        

class DOMAIN_PASSWORD_INFORMATION(NdrStructure):
    MEMBERS = [(UNSIGNED_SHORT, "MinPasswordLength"),(UNSIGNED_SHORT, "PasswordHistoryLength"),(UNSIGNED_LONG, "PasswordProperties"),(OLD_LARGE_INTEGER, "MaxPasswordAge"),(OLD_LARGE_INTEGER, "MinPasswordAge"),]

    
PDOMAIN_PASSWORD_INFORMATION = DOMAIN_PASSWORD_INFORMATION

class DOMAIN_LOGOFF_INFORMATION(NdrStructure):
    MEMBERS = [(OLD_LARGE_INTEGER, "ForceLogoff"),]

    
PDOMAIN_LOGOFF_INFORMATION = DOMAIN_LOGOFF_INFORMATION

class DOMAIN_SERVER_ROLE_INFORMATION(NdrStructure):
    MEMBERS = [(DOMAIN_SERVER_ROLE, "DomainServerRole"),]

    
PDOMAIN_SERVER_ROLE_INFORMATION = DOMAIN_SERVER_ROLE_INFORMATION

class DOMAIN_MODIFIED_INFORMATION(NdrStructure):
    MEMBERS = [(OLD_LARGE_INTEGER, "DomainModifiedCount"),(OLD_LARGE_INTEGER, "CreationTime"),]

    
PDOMAIN_MODIFIED_INFORMATION = DOMAIN_MODIFIED_INFORMATION

class DOMAIN_MODIFIED_INFORMATION2(NdrStructure):
    MEMBERS = [(OLD_LARGE_INTEGER, "DomainModifiedCount"),(OLD_LARGE_INTEGER, "CreationTime"),(OLD_LARGE_INTEGER, "ModifiedCountAtLastPromotion"),]

    
PDOMAIN_MODIFIED_INFORMATION2 = DOMAIN_MODIFIED_INFORMATION2

class SAMPR_DOMAIN_GENERAL_INFORMATION(NdrStructure):
    MEMBERS = [(OLD_LARGE_INTEGER, "ForceLogoff"),(RPC_UNICODE_STRING, "OemInformation"),(RPC_UNICODE_STRING, "DomainName"),(RPC_UNICODE_STRING, "ReplicaSourceNodeName"),(OLD_LARGE_INTEGER, "DomainModifiedCount"),(UNSIGNED_LONG, "DomainServerState"),(UNSIGNED_LONG, "DomainServerRole"),(UNSIGNED_CHAR, "UasCompatibilityRequired"),(UNSIGNED_LONG, "UserCount"),(UNSIGNED_LONG, "GroupCount"),(UNSIGNED_LONG, "AliasCount"),]

    
PSAMPR_DOMAIN_GENERAL_INFORMATION = SAMPR_DOMAIN_GENERAL_INFORMATION

class SAMPR_DOMAIN_GENERAL_INFORMATION2(NdrStructure):
    MEMBERS = [(SAMPR_DOMAIN_GENERAL_INFORMATION, "I1"),(LARGE_INTEGER, "LockoutDuration"),(LARGE_INTEGER, "LockoutObservationWindow"),(UNSIGNED_SHORT, "LockoutThreshold"),]

    
PSAMPR_DOMAIN_GENERAL_INFORMATION2 = SAMPR_DOMAIN_GENERAL_INFORMATION2

class SAMPR_DOMAIN_OEM_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "OemInformation"),]

    
PSAMPR_DOMAIN_OEM_INFORMATION = SAMPR_DOMAIN_OEM_INFORMATION

class SAMPR_DOMAIN_NAME_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "DomainName"),]

    
PSAMPR_DOMAIN_NAME_INFORMATION = SAMPR_DOMAIN_NAME_INFORMATION

class SAMPR_DOMAIN_REPLICATION_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "ReplicaSourceNodeName"),]

    
PSAMPR_DOMAIN_REPLICATION_INFORMATION = SAMPR_DOMAIN_REPLICATION_INFORMATION

class SAMPR_DOMAIN_LOCKOUT_INFORMATION(NdrStructure):
    MEMBERS = [(LARGE_INTEGER, "LockoutDuration"),(LARGE_INTEGER, "LockoutObservationWindow"),(UNSIGNED_SHORT, "LockoutThreshold"),]

    
PSAMPR_DOMAIN_LOCKOUT_INFORMATION = SAMPR_DOMAIN_LOCKOUT_INFORMATION

class DOMAIN_INFORMATION_CLASS(NdrEnum):
    MAP = ((1 , 'DomainPasswordInformation'),(2 , 'DomainGeneralInformation'),(3 , 'DomainLogoffInformation'),(4 , 'DomainOemInformation'),(5 , 'DomainNameInformation'),(6 , 'DomainReplicationInformation'),(7 , 'DomainServerRoleInformation'),(8 , 'DomainModifiedInformation'),(9 , 'DomainStateInformation'),(11 , 'DomainGeneralInformation2'),(12 , 'DomainLockoutInformation'),(13 , 'DomainModifiedInformation2'),)        

class SAMPR_DOMAIN_INFO_BUFFER(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (DOMAIN_PASSWORD_INFORMATION, "Password"),2 : (SAMPR_DOMAIN_GENERAL_INFORMATION, "General"),3 : (DOMAIN_LOGOFF_INFORMATION, "Logoff"),4 : (SAMPR_DOMAIN_OEM_INFORMATION, "Oem"),5 : (SAMPR_DOMAIN_NAME_INFORMATION, "Name"),6 : (DOMAIN_SERVER_ROLE_INFORMATION, "Role"),7 : (SAMPR_DOMAIN_REPLICATION_INFORMATION, "Replication"),8 : (DOMAIN_MODIFIED_INFORMATION, "Modified"),9 : (DOMAIN_STATE_INFORMATION, "State"),10 : (SAMPR_DOMAIN_GENERAL_INFORMATION2, "General2"),11 : (SAMPR_DOMAIN_LOCKOUT_INFORMATION, "Lockout"),12 : (DOMAIN_MODIFIED_INFORMATION2, "Modified2"),}

    
PSAMPR_DOMAIN_INFO_BUFFER = SAMPR_DOMAIN_INFO_BUFFER

class DOMAIN_DISPLAY_INFORMATION(NdrEnum):
    MAP = ((1 , 'DomainDisplayUser'),(2 , 'DomainDisplayMachine'),(3 , 'DomainDisplayGroup'),(4 , 'DomainDisplayOemUser'),(5 , 'DomainDisplayOemGroup'),)        

class SAMPR_DOMAIN_DISPLAY_USER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Index"),(UNSIGNED_LONG, "Rid"),(UNSIGNED_LONG, "AccountControl"),(RPC_UNICODE_STRING, "AccountName"),(RPC_UNICODE_STRING, "AdminComment"),(RPC_UNICODE_STRING, "FullName"),]

    
PSAMPR_DOMAIN_DISPLAY_USER = SAMPR_DOMAIN_DISPLAY_USER

class SAMPR_DOMAIN_DISPLAY_MACHINE(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Index"),(UNSIGNED_LONG, "Rid"),(UNSIGNED_LONG, "AccountControl"),(RPC_UNICODE_STRING, "AccountName"),(RPC_UNICODE_STRING, "AdminComment"),]

    
PSAMPR_DOMAIN_DISPLAY_MACHINE = SAMPR_DOMAIN_DISPLAY_MACHINE

class SAMPR_DOMAIN_DISPLAY_GROUP(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Index"),(UNSIGNED_LONG, "Rid"),(UNSIGNED_LONG, "Attributes"),(RPC_UNICODE_STRING, "AccountName"),(RPC_UNICODE_STRING, "AdminComment"),]

    
PSAMPR_DOMAIN_DISPLAY_GROUP = SAMPR_DOMAIN_DISPLAY_GROUP

class SAMPR_DOMAIN_DISPLAY_OEM_USER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Index"),(RPC_STRING, "OemAccountName"),]

    
PSAMPR_DOMAIN_DISPLAY_OEM_USER = SAMPR_DOMAIN_DISPLAY_OEM_USER

class SAMPR_DOMAIN_DISPLAY_OEM_GROUP(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Index"),(RPC_STRING, "OemAccountName"),]

    
PSAMPR_DOMAIN_DISPLAY_OEM_GROUP = SAMPR_DOMAIN_DISPLAY_OEM_GROUP

class SAMPR_DOMAIN_DISPLAY_USER_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "EntriesRead"),(PSAMPR_DOMAIN_DISPLAY_USER, "Buffer"),]

    
PSAMPR_DOMAIN_DISPLAY_USER_BUFFER = SAMPR_DOMAIN_DISPLAY_USER_BUFFER

class SAMPR_DOMAIN_DISPLAY_MACHINE_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "EntriesRead"),(PSAMPR_DOMAIN_DISPLAY_MACHINE, "Buffer"),]

    
PSAMPR_DOMAIN_DISPLAY_MACHINE_BUFFER = SAMPR_DOMAIN_DISPLAY_MACHINE_BUFFER

class SAMPR_DOMAIN_DISPLAY_GROUP_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "EntriesRead"),(PSAMPR_DOMAIN_DISPLAY_GROUP, "Buffer"),]

    
PSAMPR_DOMAIN_DISPLAY_GROUP_BUFFER = SAMPR_DOMAIN_DISPLAY_GROUP_BUFFER

class SAMPR_DOMAIN_DISPLAY_OEM_USER_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "EntriesRead"),(PSAMPR_DOMAIN_DISPLAY_OEM_USER, "Buffer"),]

    
PSAMPR_DOMAIN_DISPLAY_OEM_USER_BUFFER = SAMPR_DOMAIN_DISPLAY_OEM_USER_BUFFER

class SAMPR_DOMAIN_DISPLAY_OEM_GROUP_BUFFER(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "EntriesRead"),(PSAMPR_DOMAIN_DISPLAY_OEM_GROUP, "Buffer"),]

    
PSAMPR_DOMAIN_DISPLAY_OEM_GROUP_BUFFER = SAMPR_DOMAIN_DISPLAY_OEM_GROUP_BUFFER

class SAMPR_DISPLAY_INFO_BUFFER(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (SAMPR_DOMAIN_DISPLAY_USER_BUFFER, "UserInformation"),2 : (SAMPR_DOMAIN_DISPLAY_MACHINE_BUFFER, "MachineInformation"),3 : (SAMPR_DOMAIN_DISPLAY_GROUP_BUFFER, "GroupInformation"),4 : (SAMPR_DOMAIN_DISPLAY_OEM_USER_BUFFER, "OemUserInformation"),5 : (SAMPR_DOMAIN_DISPLAY_OEM_GROUP_BUFFER, "OemGroupInformation"),}

    
PSAMPR_DISPLAY_INFO_BUFFER = SAMPR_DISPLAY_INFO_BUFFER

class GROUP_ATTRIBUTE_INFORMATION(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Attributes"),]

    
PGROUP_ATTRIBUTE_INFORMATION = GROUP_ATTRIBUTE_INFORMATION

class SAMPR_GROUP_GENERAL_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "Name"),(UNSIGNED_LONG, "Attributes"),(UNSIGNED_LONG, "MemberCount"),(RPC_UNICODE_STRING, "AdminComment"),]

    
PSAMPR_GROUP_GENERAL_INFORMATION = SAMPR_GROUP_GENERAL_INFORMATION

class SAMPR_GROUP_NAME_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "Name"),]

    
PSAMPR_GROUP_NAME_INFORMATION = SAMPR_GROUP_NAME_INFORMATION

class SAMPR_GROUP_ADM_COMMENT_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "AdminComment"),]

    
PSAMPR_GROUP_ADM_COMMENT_INFORMATION = SAMPR_GROUP_ADM_COMMENT_INFORMATION

class GROUP_INFORMATION_CLASS(NdrEnum):
    MAP = ((1 , 'GroupGeneralInformation'),(2 , 'GroupNameInformation'),(3 , 'GroupAttributeInformation'),(4 , 'GroupAdminCommentInformation'),(5 , 'GroupReplicationInformation'),)        

class SAMPR_GROUP_INFO_BUFFER(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (SAMPR_GROUP_GENERAL_INFORMATION, "General"),2 : (SAMPR_GROUP_NAME_INFORMATION, "Name"),3 : (GROUP_ATTRIBUTE_INFORMATION, "Attribute"),4 : (SAMPR_GROUP_ADM_COMMENT_INFORMATION, "AdminComment"),5 : (SAMPR_GROUP_GENERAL_INFORMATION, "DoNotUse"),}

    
PSAMPR_GROUP_INFO_BUFFER = SAMPR_GROUP_INFO_BUFFER

class SAMPR_ALIAS_GENERAL_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "Name"),(UNSIGNED_LONG, "MemberCount"),(RPC_UNICODE_STRING, "AdminComment"),]

    
PSAMPR_ALIAS_GENERAL_INFORMATION = SAMPR_ALIAS_GENERAL_INFORMATION

class SAMPR_ALIAS_NAME_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "Name"),]

    
PSAMPR_ALIAS_NAME_INFORMATION = SAMPR_ALIAS_NAME_INFORMATION

class SAMPR_ALIAS_ADM_COMMENT_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "AdminComment"),]

    
PSAMPR_ALIAS_ADM_COMMENT_INFORMATION = SAMPR_ALIAS_ADM_COMMENT_INFORMATION

class ALIAS_INFORMATION_CLASS(NdrEnum):
    MAP = ((1 , 'AliasGeneralInformation'),(2 , 'AliasNameInformation'),(3 , 'AliasAdminCommentInformation'),)        

class SAMPR_ALIAS_INFO_BUFFER(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (SAMPR_ALIAS_GENERAL_INFORMATION, "General"),2 : (SAMPR_ALIAS_NAME_INFORMATION, "Name"),3 : (SAMPR_ALIAS_ADM_COMMENT_INFORMATION, "AdminComment"),}

    
PSAMPR_ALIAS_INFO_BUFFER = SAMPR_ALIAS_INFO_BUFFER

class SAMPR_ENCRYPTED_USER_PASSWORD(NdrStructure):
    MEMBERS = [(UNSIGNED_CHAR, "Buffer"),]

    
PSAMPR_ENCRYPTED_USER_PASSWORD = SAMPR_ENCRYPTED_USER_PASSWORD

class SAMPR_ENCRYPTED_USER_PASSWORD_NEW(NdrStructure):
    MEMBERS = [(UNSIGNED_CHAR, "Buffer"),]

    
PSAMPR_ENCRYPTED_USER_PASSWORD_NEW = SAMPR_ENCRYPTED_USER_PASSWORD_NEW

class USER_PRIMARY_GROUP_INFORMATION(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "PrimaryGroupId"),]

    
PUSER_PRIMARY_GROUP_INFORMATION = USER_PRIMARY_GROUP_INFORMATION

class USER_CONTROL_INFORMATION(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "UserAccountControl"),]

    
PUSER_CONTROL_INFORMATION = USER_CONTROL_INFORMATION

class USER_EXPIRES_INFORMATION(NdrStructure):
    MEMBERS = [(OLD_LARGE_INTEGER, "AccountExpires"),]

    
PUSER_EXPIRES_INFORMATION = USER_EXPIRES_INFORMATION

class SAMPR_LOGON_HOURS(NdrStructure):
    MEMBERS = [(UNSIGNED_SHORT, "UnitsPerWeek"),(PUNSIGNED_CHAR, "LogonHours"),]

    
PSAMPR_LOGON_HOURS = SAMPR_LOGON_HOURS

class SAMPR_USER_ALL_INFORMATION(NdrStructure):
    MEMBERS = [(OLD_LARGE_INTEGER, "LastLogon"),(OLD_LARGE_INTEGER, "LastLogoff"),(OLD_LARGE_INTEGER, "PasswordLastSet"),(OLD_LARGE_INTEGER, "AccountExpires"),(OLD_LARGE_INTEGER, "PasswordCanChange"),(OLD_LARGE_INTEGER, "PasswordMustChange"),(RPC_UNICODE_STRING, "UserName"),(RPC_UNICODE_STRING, "FullName"),(RPC_UNICODE_STRING, "HomeDirectory"),(RPC_UNICODE_STRING, "HomeDirectoryDrive"),(RPC_UNICODE_STRING, "ScriptPath"),(RPC_UNICODE_STRING, "ProfilePath"),(RPC_UNICODE_STRING, "AdminComment"),(RPC_UNICODE_STRING, "WorkStations"),(RPC_UNICODE_STRING, "UserComment"),(RPC_UNICODE_STRING, "Parameters"),(RPC_SHORT_BLOB, "LmOwfPassword"),(RPC_SHORT_BLOB, "NtOwfPassword"),(RPC_UNICODE_STRING, "PrivateData"),(SAMPR_SR_SECURITY_DESCRIPTOR, "SecurityDescriptor"),(UNSIGNED_LONG, "UserId"),(UNSIGNED_LONG, "PrimaryGroupId"),(UNSIGNED_LONG, "UserAccountControl"),(UNSIGNED_LONG, "WhichFields"),(SAMPR_LOGON_HOURS, "LogonHours"),(UNSIGNED_SHORT, "BadPasswordCount"),(UNSIGNED_SHORT, "LogonCount"),(UNSIGNED_SHORT, "CountryCode"),(UNSIGNED_SHORT, "CodePage"),(UNSIGNED_CHAR, "LmPasswordPresent"),(UNSIGNED_CHAR, "NtPasswordPresent"),(UNSIGNED_CHAR, "PasswordExpired"),(UNSIGNED_CHAR, "PrivateDataSensitive"),]

    
PSAMPR_USER_ALL_INFORMATION = SAMPR_USER_ALL_INFORMATION

class SAMPR_USER_GENERAL_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "UserName"),(RPC_UNICODE_STRING, "FullName"),(UNSIGNED_LONG, "PrimaryGroupId"),(RPC_UNICODE_STRING, "AdminComment"),(RPC_UNICODE_STRING, "UserComment"),]

    
PSAMPR_USER_GENERAL_INFORMATION = SAMPR_USER_GENERAL_INFORMATION

class SAMPR_USER_PREFERENCES_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "UserComment"),(RPC_UNICODE_STRING, "Reserved1"),(UNSIGNED_SHORT, "CountryCode"),(UNSIGNED_SHORT, "CodePage"),]

    
PSAMPR_USER_PREFERENCES_INFORMATION = SAMPR_USER_PREFERENCES_INFORMATION

class SAMPR_USER_PARAMETERS_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "Parameters"),]

    
PSAMPR_USER_PARAMETERS_INFORMATION = SAMPR_USER_PARAMETERS_INFORMATION

class SAMPR_USER_LOGON_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "UserName"),(RPC_UNICODE_STRING, "FullName"),(UNSIGNED_LONG, "UserId"),(UNSIGNED_LONG, "PrimaryGroupId"),(RPC_UNICODE_STRING, "HomeDirectory"),(RPC_UNICODE_STRING, "HomeDirectoryDrive"),(RPC_UNICODE_STRING, "ScriptPath"),(RPC_UNICODE_STRING, "ProfilePath"),(RPC_UNICODE_STRING, "WorkStations"),(OLD_LARGE_INTEGER, "LastLogon"),(OLD_LARGE_INTEGER, "LastLogoff"),(OLD_LARGE_INTEGER, "PasswordLastSet"),(OLD_LARGE_INTEGER, "PasswordCanChange"),(OLD_LARGE_INTEGER, "PasswordMustChange"),(SAMPR_LOGON_HOURS, "LogonHours"),(UNSIGNED_SHORT, "BadPasswordCount"),(UNSIGNED_SHORT, "LogonCount"),(UNSIGNED_LONG, "UserAccountControl"),]

    
PSAMPR_USER_LOGON_INFORMATION = SAMPR_USER_LOGON_INFORMATION

class SAMPR_USER_ACCOUNT_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "UserName"),(RPC_UNICODE_STRING, "FullName"),(UNSIGNED_LONG, "UserId"),(UNSIGNED_LONG, "PrimaryGroupId"),(RPC_UNICODE_STRING, "HomeDirectory"),(RPC_UNICODE_STRING, "HomeDirectoryDrive"),(RPC_UNICODE_STRING, "ScriptPath"),(RPC_UNICODE_STRING, "ProfilePath"),(RPC_UNICODE_STRING, "AdminComment"),(RPC_UNICODE_STRING, "WorkStations"),(OLD_LARGE_INTEGER, "LastLogon"),(OLD_LARGE_INTEGER, "LastLogoff"),(SAMPR_LOGON_HOURS, "LogonHours"),(UNSIGNED_SHORT, "BadPasswordCount"),(UNSIGNED_SHORT, "LogonCount"),(OLD_LARGE_INTEGER, "PasswordLastSet"),(OLD_LARGE_INTEGER, "AccountExpires"),(UNSIGNED_LONG, "UserAccountControl"),]

    
PSAMPR_USER_ACCOUNT_INFORMATION = SAMPR_USER_ACCOUNT_INFORMATION

class SAMPR_USER_A_NAME_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "UserName"),]

    
PSAMPR_USER_A_NAME_INFORMATION = SAMPR_USER_A_NAME_INFORMATION

class SAMPR_USER_F_NAME_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "FullName"),]

    
PSAMPR_USER_F_NAME_INFORMATION = SAMPR_USER_F_NAME_INFORMATION

class SAMPR_USER_NAME_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "UserName"),(RPC_UNICODE_STRING, "FullName"),]

    
PSAMPR_USER_NAME_INFORMATION = SAMPR_USER_NAME_INFORMATION

class SAMPR_USER_HOME_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "HomeDirectory"),(RPC_UNICODE_STRING, "HomeDirectoryDrive"),]

    
PSAMPR_USER_HOME_INFORMATION = SAMPR_USER_HOME_INFORMATION

class SAMPR_USER_SCRIPT_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "ScriptPath"),]

    
PSAMPR_USER_SCRIPT_INFORMATION = SAMPR_USER_SCRIPT_INFORMATION

class SAMPR_USER_PROFILE_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "ProfilePath"),]

    
PSAMPR_USER_PROFILE_INFORMATION = SAMPR_USER_PROFILE_INFORMATION

class SAMPR_USER_ADMIN_COMMENT_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "AdminComment"),]

    
PSAMPR_USER_ADMIN_COMMENT_INFORMATION = SAMPR_USER_ADMIN_COMMENT_INFORMATION

class SAMPR_USER_WORKSTATIONS_INFORMATION(NdrStructure):
    MEMBERS = [(RPC_UNICODE_STRING, "WorkStations"),]

    
PSAMPR_USER_WORKSTATIONS_INFORMATION = SAMPR_USER_WORKSTATIONS_INFORMATION

class SAMPR_USER_LOGON_HOURS_INFORMATION(NdrStructure):
    MEMBERS = [(SAMPR_LOGON_HOURS, "LogonHours"),]

    
PSAMPR_USER_LOGON_HOURS_INFORMATION = SAMPR_USER_LOGON_HOURS_INFORMATION

class SAMPR_USER_INTERNAL1_INFORMATION(NdrStructure):
    MEMBERS = [(ENCRYPTED_NT_OWF_PASSWORD, "EncryptedNtOwfPassword"),(ENCRYPTED_LM_OWF_PASSWORD, "EncryptedLmOwfPassword"),(UNSIGNED_CHAR, "NtPasswordPresent"),(UNSIGNED_CHAR, "LmPasswordPresent"),(UNSIGNED_CHAR, "PasswordExpired"),]

    
PSAMPR_USER_INTERNAL1_INFORMATION = SAMPR_USER_INTERNAL1_INFORMATION

class SAMPR_USER_INTERNAL4_INFORMATION(NdrStructure):
    MEMBERS = [(SAMPR_USER_ALL_INFORMATION, "I1"),(SAMPR_ENCRYPTED_USER_PASSWORD, "UserPassword"),]

    
PSAMPR_USER_INTERNAL4_INFORMATION = SAMPR_USER_INTERNAL4_INFORMATION

class SAMPR_USER_INTERNAL4_INFORMATION_NEW(NdrStructure):
    MEMBERS = [(SAMPR_USER_ALL_INFORMATION, "I1"),(SAMPR_ENCRYPTED_USER_PASSWORD_NEW, "UserPassword"),]

    
PSAMPR_USER_INTERNAL4_INFORMATION_NEW = SAMPR_USER_INTERNAL4_INFORMATION_NEW

class SAMPR_USER_INTERNAL5_INFORMATION(NdrStructure):
    MEMBERS = [(SAMPR_ENCRYPTED_USER_PASSWORD, "UserPassword"),(UNSIGNED_CHAR, "PasswordExpired"),]

    
PSAMPR_USER_INTERNAL5_INFORMATION = SAMPR_USER_INTERNAL5_INFORMATION

class SAMPR_USER_INTERNAL5_INFORMATION_NEW(NdrStructure):
    MEMBERS = [(SAMPR_ENCRYPTED_USER_PASSWORD_NEW, "UserPassword"),(UNSIGNED_CHAR, "PasswordExpired"),]

    
PSAMPR_USER_INTERNAL5_INFORMATION_NEW = SAMPR_USER_INTERNAL5_INFORMATION_NEW

class SAMPR_ENCRYPTED_PASSWORD_AES(NdrStructure):
    MEMBERS = [(UCHAR, "AuthData"),(UCHAR, "Salt"),(ULONG, "cbCipher"),(PUCHAR, "Cipher"),(ULONGLONG, "PBKDF2Iterations"),]

    
PSAMPR_ENCRYPTED_PASSWORD_AES = SAMPR_ENCRYPTED_PASSWORD_AES

class SAMPR_USER_INTERNAL7_INFORMATION(NdrStructure):
    MEMBERS = [(SAMPR_ENCRYPTED_PASSWORD_AES, "UserPassword"),(BOOLEAN, "PasswordExpired"),]

    
PSAMPR_USER_INTERNAL7_INFORMATION = SAMPR_USER_INTERNAL7_INFORMATION

class SAMPR_USER_INTERNAL8_INFORMATION(NdrStructure):
    MEMBERS = [(SAMPR_USER_ALL_INFORMATION, "I1"),(SAMPR_ENCRYPTED_PASSWORD_AES, "UserPassword"),]

    
PSAMPR_USER_INTERNAL8_INFORMATION = SAMPR_USER_INTERNAL8_INFORMATION

class USER_INFORMATION_CLASS(NdrEnum):
    MAP = ((1 , 'UserGeneralInformation'),(2 , 'UserPreferencesInformation'),(3 , 'UserLogonInformation'),(4 , 'UserLogonHoursInformation'),(5 , 'UserAccountInformation'),(6 , 'UserNameInformation'),(7 , 'UserAccountNameInformation'),(8 , 'UserFullNameInformation'),(9 , 'UserPrimaryGroupInformation'),(10 , 'UserHomeInformation'),(11 , 'UserScriptInformation'),(12 , 'UserProfileInformation'),(13 , 'UserAdminCommentInformation'),(14 , 'UserWorkStationsInformation'),(16 , 'UserControlInformation'),(17 , 'UserExpiresInformation'),(18 , 'UserInternal1Information'),(20 , 'UserParametersInformation'),(21 , 'UserAllInformation'),(23 , 'UserInternal4Information'),(24 , 'UserInternal5Information'),(25 , 'UserInternal4InformationNew'),(26 , 'UserInternal5InformationNew'),(31 , 'UserInternal7Information'),(32 , 'UserInternal8Information'),)        

class SAMPR_USER_INFO_BUFFER(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (SAMPR_USER_GENERAL_INFORMATION, "General"),2 : (SAMPR_USER_PREFERENCES_INFORMATION, "Preferences"),3 : (SAMPR_USER_LOGON_INFORMATION, "Logon"),4 : (SAMPR_USER_LOGON_HOURS_INFORMATION, "LogonHours"),5 : (SAMPR_USER_ACCOUNT_INFORMATION, "Account"),6 : (SAMPR_USER_NAME_INFORMATION, "Name"),7 : (SAMPR_USER_A_NAME_INFORMATION, "AccountName"),8 : (SAMPR_USER_F_NAME_INFORMATION, "FullName"),9 : (USER_PRIMARY_GROUP_INFORMATION, "PrimaryGroup"),10 : (SAMPR_USER_HOME_INFORMATION, "Home"),11 : (SAMPR_USER_SCRIPT_INFORMATION, "Script"),12 : (SAMPR_USER_PROFILE_INFORMATION, "Profile"),13 : (SAMPR_USER_ADMIN_COMMENT_INFORMATION, "AdminComment"),14 : (SAMPR_USER_WORKSTATIONS_INFORMATION, "WorkStations"),15 : (USER_CONTROL_INFORMATION, "Control"),16 : (USER_EXPIRES_INFORMATION, "Expires"),17 : (SAMPR_USER_INTERNAL1_INFORMATION, "Internal1"),18 : (SAMPR_USER_PARAMETERS_INFORMATION, "Parameters"),19 : (SAMPR_USER_ALL_INFORMATION, "All"),20 : (SAMPR_USER_INTERNAL4_INFORMATION, "Internal4"),21 : (SAMPR_USER_INTERNAL5_INFORMATION, "Internal5"),22 : (SAMPR_USER_INTERNAL4_INFORMATION_NEW, "Internal4New"),23 : (SAMPR_USER_INTERNAL5_INFORMATION_NEW, "Internal5New"),24 : (SAMPR_USER_INTERNAL7_INFORMATION, "Internal7"),25 : (SAMPR_USER_INTERNAL8_INFORMATION, "Internal8"),}

    
PSAMPR_USER_INFO_BUFFER = SAMPR_USER_INFO_BUFFER

class PASSWORD_POLICY_VALIDATION_TYPE(NdrEnum):
    MAP = ((1 , 'SamValidateAuthentication'),(2 , 'SamValidatePasswordChange'),(3 , 'SamValidatePasswordReset'),)        

class SAM_VALIDATE_PASSWORD_HASH(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "Length"),(PUNSIGNED_CHAR, "Hash"),]

    
PSAM_VALIDATE_PASSWORD_HASH = SAM_VALIDATE_PASSWORD_HASH

class SAM_VALIDATE_PERSISTED_FIELDS(NdrStructure):
    MEMBERS = [(UNSIGNED_LONG, "PresentFields"),(LARGE_INTEGER, "PasswordLastSet"),(LARGE_INTEGER, "BadPasswordTime"),(LARGE_INTEGER, "LockoutTime"),(UNSIGNED_LONG, "BadPasswordCount"),(UNSIGNED_LONG, "PasswordHistoryLength"),(PSAM_VALIDATE_PASSWORD_HASH, "PasswordHistory"),]

    
PSAM_VALIDATE_PERSISTED_FIELDS = SAM_VALIDATE_PERSISTED_FIELDS

class SAM_VALIDATE_VALIDATION_STATUS(NdrEnum):
    MAP = ((0 , 'SamValidateSuccess'),(1 , 'SamValidatePasswordMustChange'),(2 , 'SamValidateAccountLockedOut'),(3 , 'SamValidatePasswordExpired'),(4 , 'SamValidatePasswordIncorrect'),(5 , 'SamValidatePasswordIsInHistory'),(6 , 'SamValidatePasswordTooShort'),(7 , 'SamValidatePasswordTooLong'),(8 , 'SamValidatePasswordNotComplexEnough'),(9 , 'SamValidatePasswordTooRecent'),(10 , 'SamValidatePasswordFilterError'),)        

class SAM_VALIDATE_STANDARD_OUTPUT_ARG(NdrStructure):
    MEMBERS = [(SAM_VALIDATE_PERSISTED_FIELDS, "ChangedPersistedFields"),(SAM_VALIDATE_VALIDATION_STATUS, "ValidationStatus"),]

    
PSAM_VALIDATE_STANDARD_OUTPUT_ARG = SAM_VALIDATE_STANDARD_OUTPUT_ARG

class SAM_VALIDATE_AUTHENTICATION_INPUT_ARG(NdrStructure):
    MEMBERS = [(SAM_VALIDATE_PERSISTED_FIELDS, "InputPersistedFields"),(UNSIGNED_CHAR, "PasswordMatched"),]

    
PSAM_VALIDATE_AUTHENTICATION_INPUT_ARG = SAM_VALIDATE_AUTHENTICATION_INPUT_ARG

class SAM_VALIDATE_PASSWORD_CHANGE_INPUT_ARG(NdrStructure):
    MEMBERS = [(SAM_VALIDATE_PERSISTED_FIELDS, "InputPersistedFields"),(RPC_UNICODE_STRING, "ClearPassword"),(RPC_UNICODE_STRING, "UserAccountName"),(SAM_VALIDATE_PASSWORD_HASH, "HashedPassword"),(UNSIGNED_CHAR, "PasswordMatch"),]

    
PSAM_VALIDATE_PASSWORD_CHANGE_INPUT_ARG = SAM_VALIDATE_PASSWORD_CHANGE_INPUT_ARG

class SAM_VALIDATE_PASSWORD_RESET_INPUT_ARG(NdrStructure):
    MEMBERS = [(SAM_VALIDATE_PERSISTED_FIELDS, "InputPersistedFields"),(RPC_UNICODE_STRING, "ClearPassword"),(RPC_UNICODE_STRING, "UserAccountName"),(SAM_VALIDATE_PASSWORD_HASH, "HashedPassword"),(UNSIGNED_CHAR, "PasswordMustChangeAtNextLogon"),(UNSIGNED_CHAR, "ClearLockout"),]

    
PSAM_VALIDATE_PASSWORD_RESET_INPUT_ARG = SAM_VALIDATE_PASSWORD_RESET_INPUT_ARG

class SAM_VALIDATE_INPUT_ARG(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (SAM_VALIDATE_AUTHENTICATION_INPUT_ARG, "ValidateAuthenticationInput"),2 : (SAM_VALIDATE_PASSWORD_CHANGE_INPUT_ARG, "ValidatePasswordChangeInput"),3 : (SAM_VALIDATE_PASSWORD_RESET_INPUT_ARG, "ValidatePasswordResetInput"),}

    
PSAM_VALIDATE_INPUT_ARG = SAM_VALIDATE_INPUT_ARG

class SAM_VALIDATE_OUTPUT_ARG(NdrUnion):
    SWITCHTYPE = DWORD
    MEMBERS = {1 : (SAM_VALIDATE_STANDARD_OUTPUT_ARG, "ValidateAuthenticationOutput"),2 : (SAM_VALIDATE_STANDARD_OUTPUT_ARG, "ValidatePasswordChangeOutput"),3 : (SAM_VALIDATE_STANDARD_OUTPUT_ARG, "ValidatePasswordResetOutput"),}

    
PSAM_VALIDATE_OUTPUT_ARG = SAM_VALIDATE_OUTPUT_ARG
Interface("12345778-1234-ABCD-EF00-0123456789AC", "1.0",[Method("SamrConnect",
In((PSAMPR_SERVER_NAME,'ServerName')),
Out((PSAMPR_HANDLE,'ServerHandle')),
In((UNSIGNED_LONG,'DesiredAccess')),
),Method("SamrCloseHandle",
InOut((PSAMPR_HANDLE,'SamHandle')),
),Method("SamrSetSecurityObject",
In((SAMPR_HANDLE,'ObjectHandle')),
In((SECURITY_INFORMATION,'SecurityInformation')),
In((PSAMPR_SR_SECURITY_DESCRIPTOR,'SecurityDescriptor')),
),Method("SamrQuerySecurityObject",
In((SAMPR_HANDLE,'ObjectHandle')),
In((SECURITY_INFORMATION,'SecurityInformation')),
Out((PPSAMPR_SR_SECURITY_DESCRIPTOR,'SecurityDescriptor')),
),Method("Opnum4NotUsedOnWire",
),Method("SamrLookupDomainInSamServer",
In((SAMPR_HANDLE,'ServerHandle')),
In((PRPC_UNICODE_STRING,'Name')),
Out((PPRPC_SID,'DomainId')),
),Method("SamrEnumerateDomainsInSamServer",
In((SAMPR_HANDLE,'ServerHandle')),
InOut((PUNSIGNED_LONG,'EnumerationContext')),
Out((PPSAMPR_ENUMERATION_BUFFER,'Buffer')),
In((UNSIGNED_LONG,'PreferedMaximumLength')),
Out((PUNSIGNED_LONG,'CountReturned')),
),Method("SamrOpenDomain",
In((SAMPR_HANDLE,'ServerHandle')),
In((UNSIGNED_LONG,'DesiredAccess')),
In((PRPC_SID,'DomainId')),
Out((PSAMPR_HANDLE,'DomainHandle')),
),Method("SamrQueryInformationDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_INFORMATION_CLASS,'DomainInformationClass')),
Out((PPSAMPR_DOMAIN_INFO_BUFFER,'Buffer')),
),Method("SamrSetInformationDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_INFORMATION_CLASS,'DomainInformationClass')),
In((PSAMPR_DOMAIN_INFO_BUFFER,'DomainInformation')),
),Method("SamrCreateGroupInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((PRPC_UNICODE_STRING,'Name')),
In((UNSIGNED_LONG,'DesiredAccess')),
Out((PSAMPR_HANDLE,'GroupHandle')),
Out((PUNSIGNED_LONG,'RelativeId')),
),Method("SamrEnumerateGroupsInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
InOut((PUNSIGNED_LONG,'EnumerationContext')),
Out((PPSAMPR_ENUMERATION_BUFFER,'Buffer')),
In((UNSIGNED_LONG,'PreferedMaximumLength')),
Out((PUNSIGNED_LONG,'CountReturned')),
),Method("SamrCreateUserInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((PRPC_UNICODE_STRING,'Name')),
In((UNSIGNED_LONG,'DesiredAccess')),
Out((PSAMPR_HANDLE,'UserHandle')),
Out((PUNSIGNED_LONG,'RelativeId')),
),Method("SamrEnumerateUsersInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
InOut((PUNSIGNED_LONG,'EnumerationContext')),
In((UNSIGNED_LONG,'UserAccountControl')),
Out((PPSAMPR_ENUMERATION_BUFFER,'Buffer')),
In((UNSIGNED_LONG,'PreferedMaximumLength')),
Out((PUNSIGNED_LONG,'CountReturned')),
),Method("SamrCreateAliasInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((PRPC_UNICODE_STRING,'AccountName')),
In((UNSIGNED_LONG,'DesiredAccess')),
Out((PSAMPR_HANDLE,'AliasHandle')),
Out((PUNSIGNED_LONG,'RelativeId')),
),Method("SamrEnumerateAliasesInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
InOut((PUNSIGNED_LONG,'EnumerationContext')),
Out((PPSAMPR_ENUMERATION_BUFFER,'Buffer')),
In((UNSIGNED_LONG,'PreferedMaximumLength')),
Out((PUNSIGNED_LONG,'CountReturned')),
),Method("SamrGetAliasMembership",
In((SAMPR_HANDLE,'DomainHandle')),
In((PSAMPR_PSID_ARRAY,'SidArray')),
Out((PSAMPR_ULONG_ARRAY,'Membership')),
),Method("SamrLookupNamesInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((UNSIGNED_LONG,'Count')),
In((RPC_UNICODE_STRING,'Names')),
Out((PSAMPR_ULONG_ARRAY,'RelativeIds')),
Out((PSAMPR_ULONG_ARRAY,'Use')),
),Method("SamrLookupIdsInDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((UNSIGNED_LONG,'Count')),
In((PUNSIGNED_LONG,'RelativeIds')),
Out((PSAMPR_RETURNED_USTRING_ARRAY,'Names')),
Out((PSAMPR_ULONG_ARRAY,'Use')),
),Method("SamrOpenGroup",
In((SAMPR_HANDLE,'DomainHandle')),
In((UNSIGNED_LONG,'DesiredAccess')),
In((UNSIGNED_LONG,'GroupId')),
Out((PSAMPR_HANDLE,'GroupHandle')),
),Method("SamrQueryInformationGroup",
In((SAMPR_HANDLE,'GroupHandle')),
In((GROUP_INFORMATION_CLASS,'GroupInformationClass')),
Out((PPSAMPR_GROUP_INFO_BUFFER,'Buffer')),
),Method("SamrSetInformationGroup",
In((SAMPR_HANDLE,'GroupHandle')),
In((GROUP_INFORMATION_CLASS,'GroupInformationClass')),
In((PSAMPR_GROUP_INFO_BUFFER,'Buffer')),
),Method("SamrAddMemberToGroup",
In((SAMPR_HANDLE,'GroupHandle')),
In((UNSIGNED_LONG,'MemberId')),
In((UNSIGNED_LONG,'Attributes')),
),Method("SamrDeleteGroup",
InOut((PSAMPR_HANDLE,'GroupHandle')),
),Method("SamrRemoveMemberFromGroup",
In((SAMPR_HANDLE,'GroupHandle')),
In((UNSIGNED_LONG,'MemberId')),
),Method("SamrGetMembersInGroup",
In((SAMPR_HANDLE,'GroupHandle')),
Out((PPSAMPR_GET_MEMBERS_BUFFER,'Members')),
),Method("SamrSetMemberAttributesOfGroup",
In((SAMPR_HANDLE,'GroupHandle')),
In((UNSIGNED_LONG,'MemberId')),
In((UNSIGNED_LONG,'Attributes')),
),Method("SamrOpenAlias",
In((SAMPR_HANDLE,'DomainHandle')),
In((UNSIGNED_LONG,'DesiredAccess')),
In((UNSIGNED_LONG,'AliasId')),
Out((PSAMPR_HANDLE,'AliasHandle')),
),Method("SamrQueryInformationAlias",
In((SAMPR_HANDLE,'AliasHandle')),
In((ALIAS_INFORMATION_CLASS,'AliasInformationClass')),
Out((PPSAMPR_ALIAS_INFO_BUFFER,'Buffer')),
),Method("SamrSetInformationAlias",
In((SAMPR_HANDLE,'AliasHandle')),
In((ALIAS_INFORMATION_CLASS,'AliasInformationClass')),
In((PSAMPR_ALIAS_INFO_BUFFER,'Buffer')),
),Method("SamrDeleteAlias",
InOut((PSAMPR_HANDLE,'AliasHandle')),
),Method("SamrAddMemberToAlias",
In((SAMPR_HANDLE,'AliasHandle')),
In((PRPC_SID,'MemberId')),
),Method("SamrRemoveMemberFromAlias",
In((SAMPR_HANDLE,'AliasHandle')),
In((PRPC_SID,'MemberId')),
),Method("SamrGetMembersInAlias",
In((SAMPR_HANDLE,'AliasHandle')),
Out((PSAMPR_PSID_ARRAY_OUT,'Members')),
),Method("SamrOpenUser",
In((SAMPR_HANDLE,'DomainHandle')),
In((UNSIGNED_LONG,'DesiredAccess')),
In((UNSIGNED_LONG,'UserId')),
Out((PSAMPR_HANDLE,'UserHandle')),
),Method("SamrDeleteUser",
InOut((PSAMPR_HANDLE,'UserHandle')),
),Method("SamrQueryInformationUser",
In((SAMPR_HANDLE,'UserHandle')),
In((USER_INFORMATION_CLASS,'UserInformationClass')),
Out((PPSAMPR_USER_INFO_BUFFER,'Buffer')),
),Method("SamrSetInformationUser",
In((SAMPR_HANDLE,'UserHandle')),
In((USER_INFORMATION_CLASS,'UserInformationClass')),
In((PSAMPR_USER_INFO_BUFFER,'Buffer')),
),Method("SamrChangePasswordUser",
In((SAMPR_HANDLE,'UserHandle')),
In((UNSIGNED_CHAR,'LmPresent')),
In((PENCRYPTED_LM_OWF_PASSWORD,'OldLmEncryptedWithNewLm')),
In((PENCRYPTED_LM_OWF_PASSWORD,'NewLmEncryptedWithOldLm')),
In((UNSIGNED_CHAR,'NtPresent')),
In((PENCRYPTED_NT_OWF_PASSWORD,'OldNtEncryptedWithNewNt')),
In((PENCRYPTED_NT_OWF_PASSWORD,'NewNtEncryptedWithOldNt')),
In((UNSIGNED_CHAR,'NtCrossEncryptionPresent')),
In((PENCRYPTED_NT_OWF_PASSWORD,'NewNtEncryptedWithNewLm')),
In((UNSIGNED_CHAR,'LmCrossEncryptionPresent')),
In((PENCRYPTED_LM_OWF_PASSWORD,'NewLmEncryptedWithNewNt')),
),Method("SamrGetGroupsForUser",
In((SAMPR_HANDLE,'UserHandle')),
Out((PPSAMPR_GET_GROUPS_BUFFER,'Groups')),
),Method("SamrQueryDisplayInformation",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_DISPLAY_INFORMATION,'DisplayInformationClass')),
In((UNSIGNED_LONG,'Index')),
In((UNSIGNED_LONG,'EntryCount')),
In((UNSIGNED_LONG,'PreferredMaximumLength')),
Out((PUNSIGNED_LONG,'TotalAvailable')),
Out((PUNSIGNED_LONG,'TotalReturned')),
Out((PSAMPR_DISPLAY_INFO_BUFFER,'Buffer')),
),Method("SamrGetDisplayEnumerationIndex",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_DISPLAY_INFORMATION,'DisplayInformationClass')),
In((PRPC_UNICODE_STRING,'Prefix')),
Out((PUNSIGNED_LONG,'Index')),
),Method("Opnum42NotUsedOnWire",
),Method("Opnum43NotUsedOnWire",
),Method("SamrGetUserDomainPasswordInformation",
In((SAMPR_HANDLE,'UserHandle')),
Out((PUSER_DOMAIN_PASSWORD_INFORMATION,'PasswordInformation')),
),Method("SamrRemoveMemberFromForeignDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((PRPC_SID,'MemberSid')),
),Method("SamrQueryInformationDomain2",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_INFORMATION_CLASS,'DomainInformationClass')),
Out((PPSAMPR_DOMAIN_INFO_BUFFER,'Buffer')),
),Method("SamrQueryInformationUser2",
In((SAMPR_HANDLE,'UserHandle')),
In((USER_INFORMATION_CLASS,'UserInformationClass')),
Out((PPSAMPR_USER_INFO_BUFFER,'Buffer')),
),Method("SamrQueryDisplayInformation2",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_DISPLAY_INFORMATION,'DisplayInformationClass')),
In((UNSIGNED_LONG,'Index')),
In((UNSIGNED_LONG,'EntryCount')),
In((UNSIGNED_LONG,'PreferredMaximumLength')),
Out((PUNSIGNED_LONG,'TotalAvailable')),
Out((PUNSIGNED_LONG,'TotalReturned')),
Out((PSAMPR_DISPLAY_INFO_BUFFER,'Buffer')),
),Method("SamrGetDisplayEnumerationIndex2",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_DISPLAY_INFORMATION,'DisplayInformationClass')),
In((PRPC_UNICODE_STRING,'Prefix')),
Out((PUNSIGNED_LONG,'Index')),
),Method("SamrCreateUser2InDomain",
In((SAMPR_HANDLE,'DomainHandle')),
In((PRPC_UNICODE_STRING,'Name')),
In((UNSIGNED_LONG,'AccountType')),
In((UNSIGNED_LONG,'DesiredAccess')),
Out((PSAMPR_HANDLE,'UserHandle')),
Out((PUNSIGNED_LONG,'GrantedAccess')),
Out((PUNSIGNED_LONG,'RelativeId')),
),Method("SamrQueryDisplayInformation3",
In((SAMPR_HANDLE,'DomainHandle')),
In((DOMAIN_DISPLAY_INFORMATION,'DisplayInformationClass')),
In((UNSIGNED_LONG,'Index')),
In((UNSIGNED_LONG,'EntryCount')),
In((UNSIGNED_LONG,'PreferredMaximumLength')),
Out((PUNSIGNED_LONG,'TotalAvailable')),
Out((PUNSIGNED_LONG,'TotalReturned')),
Out((PSAMPR_DISPLAY_INFO_BUFFER,'Buffer')),
),Method("SamrAddMultipleMembersToAlias",
In((SAMPR_HANDLE,'AliasHandle')),
In((PSAMPR_PSID_ARRAY,'MembersBuffer')),
),Method("SamrRemoveMultipleMembersFromAlias",
In((SAMPR_HANDLE,'AliasHandle')),
In((PSAMPR_PSID_ARRAY,'MembersBuffer')),
),Method("SamrOemChangePasswordUser2",
In((HANDLE_T,'BindingHandle')),
In((PRPC_STRING,'ServerName')),
In((PRPC_STRING,'UserName')),
In((PSAMPR_ENCRYPTED_USER_PASSWORD,'NewPasswordEncryptedWithOldLm')),
In((PENCRYPTED_LM_OWF_PASSWORD,'OldLmOwfPasswordEncryptedWithNewLm')),
),Method("SamrUnicodeChangePasswordUser2",
In((HANDLE_T,'BindingHandle')),
In((PRPC_UNICODE_STRING,'ServerName')),
In((PRPC_UNICODE_STRING,'UserName')),
In((PSAMPR_ENCRYPTED_USER_PASSWORD,'NewPasswordEncryptedWithOldNt')),
In((PENCRYPTED_NT_OWF_PASSWORD,'OldNtOwfPasswordEncryptedWithNewNt')),
In((UNSIGNED_CHAR,'LmPresent')),
In((PSAMPR_ENCRYPTED_USER_PASSWORD,'NewPasswordEncryptedWithOldLm')),
In((PENCRYPTED_LM_OWF_PASSWORD,'OldLmOwfPasswordEncryptedWithNewNt')),
),Method("SamrGetDomainPasswordInformation",
In((HANDLE_T,'BindingHandle')),
In((PRPC_UNICODE_STRING,'Unused')),
Out((PUSER_DOMAIN_PASSWORD_INFORMATION,'PasswordInformation')),
),Method("SamrConnect2",
In((PSAMPR_SERVER_NAME,'ServerName')),
Out((PSAMPR_HANDLE,'ServerHandle')),
In((UNSIGNED_LONG,'DesiredAccess')),
),Method("SamrSetInformationUser2",
In((SAMPR_HANDLE,'UserHandle')),
In((USER_INFORMATION_CLASS,'UserInformationClass')),
In((PSAMPR_USER_INFO_BUFFER,'Buffer')),
),Method("Opnum59NotUsedOnWire",
),Method("Opnum60NotUsedOnWire",
),Method("Opnum61NotUsedOnWire",
),Method("SamrConnect4",
In((PSAMPR_SERVER_NAME,'ServerName')),
Out((PSAMPR_HANDLE,'ServerHandle')),
In((UNSIGNED_LONG,'ClientRevision')),
In((UNSIGNED_LONG,'DesiredAccess')),
),Method("Opnum63NotUsedOnWire",
),Method("SamrConnect5",
In((PSAMPR_SERVER_NAME,'ServerName')),
In((UNSIGNED_LONG,'DesiredAccess')),
In((UNSIGNED_LONG,'InVersion')),
In((PSAMPR_REVISION_INFO,'InRevisionInfo')),
Out((PUNSIGNED_LONG,'OutVersion')),
Out((PSAMPR_REVISION_INFO,'OutRevisionInfo')),
Out((PSAMPR_HANDLE,'ServerHandle')),
),Method("SamrRidToSid",
In((SAMPR_HANDLE,'ObjectHandle')),
In((UNSIGNED_LONG,'Rid')),
Out((PPRPC_SID,'Sid')),
),Method("SamrSetDSRMPassword",
In((HANDLE_T,'BindingHandle')),
In((PRPC_UNICODE_STRING,'Unused')),
In((UNSIGNED_LONG,'UserId')),
In((PENCRYPTED_NT_OWF_PASSWORD,'EncryptedNtOwfPassword')),
),Method("SamrValidatePassword",
In((HANDLE_T,'Handle')),
In((PASSWORD_POLICY_VALIDATION_TYPE,'ValidationType')),
In((PSAM_VALIDATE_INPUT_ARG,'InputArg')),
Out((PPSAM_VALIDATE_OUTPUT_ARG,'OutputArg')),
),Method("Opnum68NotUsedOnWire",
),Method("Opnum69NotUsedOnWire",
),Method("Opnum70NotUsedOnWire",
),Method("Opnum71NotUsedOnWire",
),Method("Opnum72NotUsedOnWire",
),Method("SamrUnicodeChangePasswordUser4",
In((HANDLE_T,'BindingHandle')),
In((PRPC_UNICODE_STRING,'ServerName')),
In((PRPC_UNICODE_STRING,'UserName')),
In((PSAMPR_ENCRYPTED_PASSWORD_AES,'EncryptedPassword')),
),])