
from fuzzer.midl import *
from fuzzer.core import *
interface_0 = Interface("3919286a-b10c-11d0-9ba8-00c04fd92ef5", "0.0",[
Method("DsRolerGetPrimaryDomainInformation",
In(HANDLE_T),
In(DSROLE_PRIMARY_DOMAIN_INFO_LEVEL),
Out(PPDSROLER_PRIMARY_DOMAIN_INFORMATION),
),
Method("Opnum1NotUsedOnWire",
In(),
),
Method("Opnum2NotUsedOnWire",
In(),
),
Method("Opnum3NotUsedOnWire",
In(),
),
Method("Opnum4NotUsedOnWire",
In(),
),
Method("Opnum5NotUsedOnWire",
In(),
),
Method("Opnum6NotUsedOnWire",
In(),
),
Method("Opnum7NotUsedOnWire",
In(),
),
Method("Opnum8NotUsedOnWire",
In(),
),
Method("Opnum9NotUsedOnWire",
In(),
),
Method("Opnum10NotUsedOnWire",
In(),
),
Method("Opnum11NotUsedOnWire",
In(),
),
])
