
from fuzzer.midl import *
from fuzzer.core import *
interface_0 = Interface("44e265dd-7daf-42cd-8560-3cdb6e7a2729", "1.3",[
Method("Opnum0NotUsedOnWire",
In(),
),
Method("TsProxyCreateTunnel",
In(PTSG_PACKET),
Out(PPTSG_PACKET),
Out(PPTUNNEL_CONTEXT_HANDLE_SERIALIZE),
Out(PUNSIGNED_LONG),
),
Method("TsProxyAuthorizeTunnel",
In(PTUNNEL_CONTEXT_HANDLE_NOSERIALIZE),
In(PTSG_PACKET),
Out(PPTSG_PACKET),
),
Method("TsProxyMakeTunnelCall",
In(PTUNNEL_CONTEXT_HANDLE_NOSERIALIZE),
In(UNSIGNED_LONG),
In(PTSG_PACKET),
Out(PPTSG_PACKET),
),
Method("TsProxyCreateChannel",
In(PTUNNEL_CONTEXT_HANDLE_NOSERIALIZE),
In(PTSENDPOINTINFO),
Out(PPCHANNEL_CONTEXT_HANDLE_SERIALIZE),
Out(PUNSIGNED_LONG),
),
Method("Opnum5NotUsedOnWire",
In(),
),
Method("TsProxyCloseChannel",
InOut(PPCHANNEL_CONTEXT_HANDLE_NOSERIALIZE),
),
Method("TsProxyCloseTunnel",
InOut(PPTUNNEL_CONTEXT_HANDLE_SERIALIZE),
),
Method("TsProxySetupReceivePipe",
In(BYTE),
),
Method("TsProxySendToServer",
In(BYTE),
),
])
