from fuzzer.midl import *
from fuzzer.core import *

Method(
    "RpcAsyncOpenPrinter",
    In(HANDLE_T),
    In(PWCHAR_T),
    Out(PPRINTER_HANDLE),
    In(PWCHAR_T),
    In(PDEVMODE_CONTAINER),
    In(DWORD),
    In(PSPLCLIENT_CONTAINER),
), Method(
    "RpcAsyncAddPrinter",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PPRINTER_CONTAINER),
    In(PDEVMODE_CONTAINER),
    In(PSECURITY_CONTAINER),
    In(PSPLCLIENT_CONTAINER),
    Out(PPRINTER_HANDLE),
), Method(
    "RpcAsyncSetJob",
    In(PRINTER_HANDLE),
    In(DWORD),
    In(PJOB_CONTAINER),
    In(DWORD),
), Method(
    "RpcAsyncGetJob",
    In(PRINTER_HANDLE),
    In(DWORD),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncEnumJobs",
    In(PRINTER_HANDLE),
    In(DWORD),
    In(DWORD),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncAddJob",
    In(PRINTER_HANDLE),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncScheduleJob",
    In(PRINTER_HANDLE),
    In(DWORD),
), Method(
    "RpcAsyncDeletePrinter",
    In(PRINTER_HANDLE),
), Method(
    "RpcAsyncSetPrinter",
    In(PRINTER_HANDLE),
    In(PPRINTER_CONTAINER),
    In(PDEVMODE_CONTAINER),
    In(PSECURITY_CONTAINER),
    In(DWORD),
), Method(
    "RpcAsyncGetPrinter",
    In(PRINTER_HANDLE),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncStartDocPrinter",
    In(PRINTER_HANDLE),
    In(PDOC_INFO_CONTAINER),
    Out(PDWORD),
), Method(
    "RpcAsyncStartPagePrinter",
    In(PRINTER_HANDLE),
), Method(
    "RpcAsyncWritePrinter",
    In(PRINTER_HANDLE),
    In(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncEndPagePrinter",
    In(PRINTER_HANDLE),
), Method(
    "RpcAsyncEndDocPrinter",
    In(PRINTER_HANDLE),
), Method(
    "RpcAsyncAbortPrinter",
    In(PRINTER_HANDLE),
), Method(
    "RpcAsyncGetPrinterData",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    Out(PDWORD),
    Out(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncGetPrinterDataEx",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(PWCHAR_T),
    Out(PDWORD),
    Out(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncSetPrinterData",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(DWORD),
    In(PUNSIGNED_CHAR),
    In(DWORD),
), Method(
    "RpcAsyncSetPrinterDataEx",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    In(PUNSIGNED_CHAR),
    In(DWORD),
), Method(
    "RpcAsyncClosePrinter",
    InOut(PPRINTER_HANDLE),
), Method(
    "RpcAsyncAddForm",
    In(PRINTER_HANDLE),
    In(PFORM_CONTAINER),
), Method(
    "RpcAsyncDeleteForm",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
), Method(
    "RpcAsyncGetForm",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncSetForm",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(PFORM_CONTAINER),
), Method(
    "RpcAsyncEnumForms",
    In(PRINTER_HANDLE),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncGetPrinterDriver",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    In(DWORD),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncEnumPrinterData",
    In(PRINTER_HANDLE),
    In(DWORD),
    Out(PWCHAR_T),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
    Out(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncEnumPrinterDataEx",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    Out(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncEnumPrinterKey",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    Out(PWCHAR_T),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncDeletePrinterData",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
), Method(
    "RpcAsyncDeletePrinterDataEx",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncDeletePrinterKey",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
), Method(
    "RpcAsyncXcvData",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    InOut(PDWORD),
), Method(
    "RpcAsyncSendRecvBidiData",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(PRPC_BIDI_REQUEST_CONTAINER),
    Out(PPRPC_BIDI_RESPONSE_CONTAINER),
), Method(
    "RpcAsyncCreatePrinterIC",
    In(PRINTER_HANDLE),
    Out(PGDI_HANDLE),
    In(PDEVMODE_CONTAINER),
), Method(
    "RpcAsyncPlayGdiScriptOnPrinterIC",
    In(GDI_HANDLE),
    In(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PUNSIGNED_CHAR),
    In(DWORD),
    In(DWORD),
), Method(
    "RpcAsyncDeletePrinterIC",
    InOut(PGDI_HANDLE),
), Method(
    "RpcAsyncEnumPrinters",
    In(HANDLE_T),
    In(DWORD),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncAddPrinterDriver",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PDRIVER_CONTAINER),
    In(DWORD),
), Method(
    "RpcAsyncEnumPrinterDrivers",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncGetPrinterDriverDirectory",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncDeletePrinterDriver",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncDeletePrinterDriverEx",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    In(DWORD),
), Method(
    "RpcAsyncAddPrintProcessor",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncEnumPrintProcessors",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncGetPrintProcessorDirectory",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncEnumPorts",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncEnumMonitors",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncAddPort",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PPORT_CONTAINER),
    In(PPORT_VAR_CONTAINER),
    In(PWCHAR_T),
), Method(
    "RpcAsyncSetPort",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PPORT_CONTAINER),
), Method(
    "RpcAsyncAddMonitor",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PMONITOR_CONTAINER),
), Method(
    "RpcAsyncDeleteMonitor",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncDeletePrintProcessor",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncEnumPrintProcessorDatatypes",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncAddPerMachineConnection",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncDeletePerMachineConnection",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncEnumPerMachineConnections",
    In(HANDLE_T),
    In(PWCHAR_T),
    InOut(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
    Out(PDWORD),
), Method(
    "RpcSyncRegisterForRemoteNotifications",
    In(PRINTER_HANDLE),
    In(PRPCPRINTPROPERTIESCOLLECTION),
    Out(PRMTNTFY_HANDLE),
), Method(
    "RpcSyncUnRegisterForRemoteNotifications",
    InOut(PRMTNTFY_HANDLE),
), Method(
    "RpcSyncRefreshRemoteNotifications",
    In(RMTNTFY_HANDLE),
    In(PRPCPRINTPROPERTIESCOLLECTION),
    Out(PPRPCPRINTPROPERTIESCOLLECTION),
), Method(
    "RpcAsyncGetRemoteNotifications",
    In(RMTNTFY_HANDLE),
    Out(PPRPCPRINTPROPERTIESCOLLECTION),
), Method(
    "RpcAsyncInstallPrinterDriverFromPackage",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
), Method(
    "RpcAsyncUploadPrinterDriverPackage",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    InOut(PWCHAR_T),
    InOut(PDWORD),
), Method(
    "RpcAsyncGetCorePrinterDrivers",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(DWORD),
    In(PWCHAR_T),
    In(DWORD),
    Out(PCORE_PRINTER_DRIVER),
), Method(
    "RpcAsyncCorePrinterDriverInstalled",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(GUID),
    In(FILETIME),
    In(DWORDLONG),
    Out(PINT),
), Method(
    "RpcAsyncGetPrinterDriverPackagePath",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    InOut(PWCHAR_T),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncDeletePrinterDriverPackage",
    In(HANDLE_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
    In(PWCHAR_T),
), Method(
    "RpcAsyncReadPrinter",
    In(PRINTER_HANDLE),
    Out(PUNSIGNED_CHAR),
    In(DWORD),
    Out(PDWORD),
), Method(
    "RpcAsyncResetPrinter",
    In(PRINTER_HANDLE),
    In(PWCHAR_T),
    In(PDEVMODE_CONTAINER),
), Method(
    "RpcAsyncGetJobNamedPropertyValue",
    In(PRINTER_HANDLE),
    In(DWORD),
    In(PWCHAR_T),
    Out(PRPC_PRINTPROPERTYVALUE),
), Method(
    "RpcAsyncSetJobNamedProperty",
    In(PRINTER_HANDLE),
    In(DWORD),
    In(PRPC_PRINTNAMEDPROPERTY),
), Method(
    "RpcAsyncDeleteJobNamedProperty",
    In(PRINTER_HANDLE),
    In(DWORD),
    In(PWCHAR_T),
), Method(
    "RpcAsyncEnumJobNamedProperties",
    In(PRINTER_HANDLE),
    In(DWORD),
    Out(PDWORD),
    Out(PPRPC_PRINTNAMEDPROPERTY),
), Method(
    "RpcAsyncLogJobInfoForBranchOffice",
    In(PRINTER_HANDLE),
    In(PRPC_BRANCHOFFICEJOBDATACONTAINER),
),
