
from fuzzer.midl import *
from fuzzer.core import *
interface_0 = Interface("ccd8c074-d0e5-440-924-d074faa6ba28", "1.1",[
Method("WitnessrGetInterfaceList",
In(HANDLE_T),
Out(PPWITNESS_INTERFACE_LIST),
),
Method("WitnessrRegister",
In(HANDLE_T),
Out(PPCONTEXT_HANDLE),
In(ULONG),
In(LPWSTR),
In(LPWSTR),
In(LPWSTR),
),
Method("WitnessrUnRegister",
In(HANDLE_T),
In(PCONTEXT_HANDLE),
),
Method("WitnessrAsyncNotify",
In(HANDLE_T),
In(PCONTEXT_HANDLE_SHARED),
Out(PPRESP_ASYNC_NOTIFY),
),
Method("WitnessrRegisterEx",
In(HANDLE_T),
Out(PPCONTEXT_HANDLE),
In(ULONG),
In(LPWSTR),
In(LPWSTR),
In(LPWSTR),
In(LPWSTR),
In(ULONG),
In(ULONG),
),
])
