
from fuzzer.midl import *
from fuzzer.core import *
interface_0 = Interface("d99e6e70-fc88-110-b498-000903123", "1.0",[
Method("Request",
In(DWORD),
In(PWCHAR_T_),
InOut(PDWORD),
Out(PDWORD),
In(PWCHAR_T_),
In(PCERTTRANSBLOB_),
Out(PCERTTRANSBLOB),
Out(PCERTTRANSBLOB),
Out(PCERTTRANSBLOB),
),
Method("GetCACert",
In(DWORD),
In(PWCHAR_T_),
Out(PCERTTRANSBLOB),
),
Method("Ping",
In(PWCHAR_T_),
),
])
interface_1 = Interface("5422fd3a-d4b8-4cef-a12e-e87d4ca22e90", "1.0",[
Method("Request2",
In(PWCHAR_T_),
In(DWORD),
In(PWCHAR_T_),
InOut(PDWORD),
Out(PDWORD),
In(PWCHAR_T_),
In(PCERTTRANSBLOB_),
Out(PCERTTRANSBLOB),
Out(PCERTTRANSBLOB),
Out(PCERTTRANSBLOB),
),
Method("GetCAProperty",
In(PWCHAR_T_),
In(LONG),
In(LONG),
In(LONG),
Out(PCERTTRANSBLOB),
),
Method("GetCAPropertyInfo",
In(PWCHAR_T_),
Out(PLONG),
Out(PCERTTRANSBLOB),
),
Method("Ping2",
In(PWCHAR_T_),
),
])
